# Google App Store EDA

# Assignment:
1. Download the data
2. Extract data from zip file
3. read the data into python pandas
4. Check each column
5. Define each column in MD style

In [396]:
# %pip install ydata_profiling

In [397]:
# import libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt 

In [398]:
# import dataset

df = pd.read_csv('./data/googleplaystore.csv')

In [399]:
# commit out if you donot want to run automatic EDA Profiling

# # Run automatic EDA using ydata profiling


# # import library
# import ydata_profiling as yd

# profile = yd.ProfileReport(df)

# profile.to_file(output_file = './data/ydata_googleplaystore_kaggle.html')

In [400]:
# Check the data 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10840 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64  
 4   Size            10841 non-null  object 
 5   Installs        10841 non-null  object 
 6   Type            10840 non-null  object 
 7   Price           10841 non-null  object 
 8   Content Rating  10841 non-null  object 
 9   Genres          10840 non-null  object 
 10  Last Updated    10841 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10839 non-null  object 
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB


In [401]:
# lets have a  look on the data
df.head(6)

App         Category  Rating  \
0                     Command & Conquer: Rivals           FAMILY     NaN   
1  Popsicle Launcher for Android P 9.0 launcher  PERSONALIZATION     NaN   
2                       Ak Parti Yardım Toplama           SOCIAL     NaN   
3                        AP Series Solution Pro           FAMILY     NaN   
4                    Ain Arabic Kids Alif Ba ta           FAMILY     NaN   
5                                 cronometra-br     PRODUCTIVITY     NaN   

   Reviews                Size Installs  Type     Price Content Rating  \
0        0  Varies with device        0   NaN         0   Everyone 10+   
1        0                5.5M       0+  Paid    $1.49        Everyone   
2        0                8.7M       0+  Paid   $13.99            Teen   
3        0                7.4M       0+  Paid    $1.99        Everyone   
4        0                 33M       0+  Paid    $2.99        Everyone   
5        0                5.4M       0+  Paid  $154.99        Everyone   

            Genres Last Updated         Current Ver         Android Ver  
0         Strategy    28-Jun-18  Varies with device  Varies with device  
1  Personalization    11-Jul-18                 1.1          4.2 and up  
2           Social    28-Jul-17           3.4.4.3.3          4.1 and up  
3        Education    30-Jul-17                 1.3          4.0 and up  
4        Education    15-Apr-16                   1          3.0 and up  
5     Productivity    24-Nov-17               1.0.0          4.1 and up

In [402]:
# take samples from big dataset

df.sample(10)

App             Category  Rating  \
284           Black People Meet Singles Date               DATING     3.9   
829                  Job Korea - Career Jobs             BUSINESS     4.3   
5303                Wallpapers FN Five seven      PERSONALIZATION     NaN   
2839            Tagged - Meet, Chat & Dating               SOCIAL     4.1   
6018                           AE GTO Racing                 GAME     3.9   
3708          Stocard - Rewards Cards Wallet             SHOPPING     4.6   
331           FXNOW: Movies, Shows & Live TV               FAMILY     3.9   
9868                             EG Way Life               SOCIAL     NaN   
4951  Chess of Blades (BL/Yaoi Game) (No VA)               FAMILY     4.8   
1615             ReadEra – free ebook reader  BOOKS_AND_REFERENCE     4.8   

      Reviews                Size     Installs  Type    Price Content Rating  \
284     10212                5.0M   1,000,000+  Free        0     Mature 17+   
829     10600                6.5M   1,000,000+  Free        0       Everyone   
5303        0                 13M          10+  Free        0           Teen   
2839   486824  Varies with device  10,000,000+  Free        0     Mature 17+   
6018     6988                 35M     100,000+  Free        0   Everyone 10+   
3708   284725                 20M  10,000,000+  Free        0       Everyone   
331     31552  Varies with device   1,000,000+  Free        0           Teen   
9868        0                1.1M          50+  Free        0       Everyone   
4951        4                 23M          10+  Paid  $14.99            Teen   
1615    47303                 21M   1,000,000+  Free        0       Everyone   

                 Genres Last Updated         Current Ver         Android Ver  
284              Dating    25-Jul-18               1.9.7          4.4 and up  
829            Business     1-Aug-18               2.5.6          4.0 and up  
5303    Personalization    18-Apr-18                   1          4.1 and up  
2839             Social    21-Jun-18  Varies with device  Varies with device  
6018             Racing    24-Sep-15  Varies with device  Varies with device  
3708           Shopping    31-Jul-18               7.2.1          4.1 and up  
331       Entertainment    23-Jul-18  Varies with device          4.4 and up  
9868             Social    27-Apr-16                   1          4.1 and up  
4951             Casual    24-Jan-18                1.03        2.3.3 and up  
1615  Books & Reference     2-Jun-18        18.05.31+530          4.1 and up

In [403]:

df.describe()

Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

# Assignment: Write down all the numeric variables and make them numeric

1. size
2. install
3. price

In [404]:
# to do that let's have a look on unique values

df['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ... 
251k                     1
862k                     1
554k                     1
164k                     1
562k                     1
Name: count, Length: 461, dtype: int64

# 1. Size
### Check that how many MBs are there in one KB? and how to calculate?
1. Convert KBs into M
2. than remove M fromm all numbers
3. Handle `varies with device`.

In [405]:
df['Size'].isnull().sum()

np.int64(0)

In [406]:
# 1. Convert KBs into M
# 2. than remove M fromm all numbers
# 3. Handle `varies with device`.

# Function to convert size
def convert_size(size):
    if 'k' in size:
        return float(size.replace('k', '')) / 1024  # Convert kB to MB
    elif 'M' in size:
        return float(size.replace('M', ''))  # Already in MB
    else:
        return np.nan  # Handle non-numeric values

# Apply function to the Size column
df['Size'] = df['Size'].astype(str).apply(convert_size)


In [417]:
df["Size"].unique()

array([           nan, 5.50000000e+00, 8.70000000e+00, 7.40000000e+00,
       3.30000000e+01, 5.40000000e+00, 5.90000000e+00, 1.00000000e+01,
       2.10000000e+00, 1.20000000e+00, 5.60000000e+01, 3.20000000e+00,
       2.60000000e+00, 1.40000000e+00, 4.00000000e+01, 1.30000000e+01,
       7.60000000e+01, 3.80000000e+00, 3.30000000e+00, 3.90000000e+00,
       3.20000000e+01, 1.90000000e+01, 1.50000000e+01, 2.10000000e+01,
       3.00000000e+00, 5.30000000e+01, 4.60000000e+01, 5.50000000e+01,
       2.70000000e+00, 5.80000000e+00, 1.40000000e+01, 9.80000000e+01,
       9.60000000e+01, 9.80000000e+00, 5.00000000e+01, 5.10000000e+00,
       5.10000000e+01, 2.90000000e+01, 3.70000000e+01, 1.80000000e+01,
       7.70000000e+01, 2.70000000e+01, 1.70000000e+01, 5.00000000e+00,
       1.80000000e+00, 7.30000000e+00, 6.10000000e+01, 2.30000000e+01,
       6.10000000e+00, 8.20000000e+00, 4.10000000e+01, 5.31250000e-01,
       4.40000000e+01, 7.00000000e+00, 8.20000000e+01, 2.80000000e+01,
      

## 2. Install

1. removing the ',' and '+'
2. converting the from str to integer

In [408]:
# Before Filtering
df['Installs'].unique()

array(['0', '0+', '1,000,000,000+', '1,000,000+', '1,000+', '1+',
       '10,000,000+', '10,000+', '10+', '100,000,000+', '100,000+',
       '100+', '5,000,000+', '5,000+', '5+', '50,000,000+', '50,000+',
       '50+', '500,000,000+', '500,000+', '500+'], dtype=object)

In [409]:

# Removing the ',' and '+'
df['Installs']=df['Installs'].str.replace(',', '')
df['Installs'] = df['Installs'].str.replace('+', '')

# Type casting/conversion
df['Installs'] = df['Installs'].astype('int64')

# check data types
df.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size              float64
Installs            int64
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [410]:
# After Filtering
df['Installs'].unique()

array([         0, 1000000000,    1000000,       1000,          1,
         10000000,      10000,         10,  100000000,     100000,
              100,    5000000,       5000,          5,   50000000,
            50000,         50,  500000000,     500000,        500])

## do it as numeric column or group that into different group following binning method

### How to handle Price?

In [411]:
# Before filtering

# Unique values of Price column
df['Price'].unique()

array(['0', '$1.49 ', '$13.99 ', '$1.99 ', '$2.99 ', '$154.99 ', '$3.99 ',
       '$200.00 ', '$30.99 ', '$394.99 ', '$399.99 ', '$2.49 ', '$0.99 ',
       '$5.99 ', '$6.99 ', '$4.99 ', '$9.99 ', '$379.99 ', '$29.99 ',
       '$15.46 ', '$10.99 ', '$2.56 ', '$33.99 ', '$19.99 ', '$8.49 ',
       '$14.99 ', '$4.84 ', '$1.29 ', '$7.49 ', '$1.50 ', '$1.70 ',
       '$1.61 ', '$37.99 ', '$16.99 ', '$4.49 ', '$5.49 ', '$3.08 ',
       '$7.99 ', '$79.99 ', '$4.29 ', '$19.40 ', '$3.49 ', '$10.00 ',
       '$74.99 ', '$109.99 ', '$28.99 ', '$400.00 ', '$389.99 ',
       '$299.99 ', '$3.28 ', '$24.99 ', '$1.20 ', '$11.99 ', '$1.59 ',
       '$2.95 ', '$1.97 ', '$17.99 ', '$18.99 ', '$12.99 ', '$2.59 ',
       '$3.90 ', '$2.50 ', '$3.04 ', '$2.00 ', '$25.99 ', '$46.99 ',
       '$4.80 ', '$1.96 ', '$89.99 ', '$3.61 ', '$6.49 ', '$3.95 ',
       '$8.99 ', '$9.00 ', '$2.90 ', '$4.59 ', '$39.99 ', '$3.02 ',
       '$3.88 ', '$14.00 ', '$5.00 ', '$19.90 ', '$1.26 ', '$4.60 ',
       '$1.00 ', '$4.77

In [412]:
# Checking sum of null values in Pric column
df['Price'].isnull().sum()

np.int64(0)

In [413]:
# removing the '$' and ' ' from the specific column of dataset

df["Price"] = df['Price'].str.replace('$','').str.replace(' ','')

# Type casting/ conversion
df['Price'] = df['Price'].astype('float64')

df.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size              float64
Installs            int64
Type               object
Price             float64
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [414]:
# After Filtering

# unique values of Price column
df['Price'].unique()

array([  0.  ,   1.49,  13.99,   1.99,   2.99, 154.99,   3.99, 200.  ,
        30.99, 394.99, 399.99,   2.49,   0.99,   5.99,   6.99,   4.99,
         9.99, 379.99,  29.99,  15.46,  10.99,   2.56,  33.99,  19.99,
         8.49,  14.99,   4.84,   1.29,   7.49,   1.5 ,   1.7 ,   1.61,
        37.99,  16.99,   4.49,   5.49,   3.08,   7.99,  79.99,   4.29,
        19.4 ,   3.49,  10.  ,  74.99, 109.99,  28.99, 400.  , 389.99,
       299.99,   3.28,  24.99,   1.2 ,  11.99,   1.59,   2.95,   1.97,
        17.99,  18.99,  12.99,   2.59,   3.9 ,   2.5 ,   3.04,   2.  ,
        25.99,  46.99,   4.8 ,   1.96,  89.99,   3.61,   6.49,   3.95,
         8.99,   9.  ,   2.9 ,   4.59,  39.99,   3.02,   3.88,  14.  ,
         5.  ,  19.9 ,   1.26,   4.6 ,   1.  ,   4.77,   1.76,   1.75,
         4.85,   2.6 ,   1.04,  15.99])

## Remove $ sign from all columns using pandas

In [415]:
df['Type'].value_counts()

Type
Free    10040
Paid      800
Name: count, dtype: int64

In [416]:
df['Type'].isnull().sum()

np.int64(1)